# Generated by Django 4.2.1 on 2023-05-22 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_rename_post_id_like_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='parent',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='likes_count',
            field=models.PositiveBigIntegerField(default=0),
        ),
    ]
